HC branch 1 (#22)
* Update alignment.py

Added if/else statement for when blastp or blastn returns an empty output file due to no sequence matches being found. This results in AttributeError: 'BlastResult' object has no attribute 'qseqid', causing Bactabolize to exit before model troubleshooting occurs.

* Update draft_model.py

Added if/else statement for when blastp or blastn returns an empty output file due to no sequence matches being found. This results in AttributeError: 'BlastResult' object has no attribute 'qseqid', causing Bactabolize to exit before model troubleshooting occurs.

* Update model_fba.py

The lower bounds for all sink reactions in the model are set to zero, as having reversible sink reactions can cause incorrect FBA predictions.