Update draft_model.py
Added if/else statement for when blastp or blastn returns an empty output file due to no sequence matches being found. This results in AttributeError: 'BlastResult' object has no attribute 'qseqid', causing Bactabolize to exit before model troubleshooting occurs.